replicaCount: 1

image:
  repository: metabase
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClassName: ""
  mountPath: /metabase.db
  fileName: metabase.db

env:
  MB_DB_TYPE: h2
